server:
  port: 8082
spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      database: userdb
      uri: mongodb://localhost:27017/userdb

# eureka:
#   client:
#     service-url:
#       default-zone: http://localhost:8761/ 
