server:
  port: 8082
spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      database: userdb
      uri: mongodb://localhost:27017/userdb

# eureka:
#   client:
#     service-url:
#       default-zone: http://localhost:8761/ 

# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
logging:
  file:
    name: log/${spring.application.name}.log 
    
  logback:
    rollingpolicy:
      max-file-size:
        5 mb
      max-history: 7
